language: php # 平台环境

php: # php 版本
  - 7.1
  - 7.2

dist: trusty  # 系统版本
sudo: false   # 使用 sudo 模式

# 执行前需要运行的命令
install: travis_retry composer install --no-interaction --prefer-source

# 主要构件命令
script: vendor/bin/phpunit tests --verbose